サインアップ機能実装
shinonome-inc/backend-final-assignment-Shintaro_Shimura pull request #1
Opened 2023-06-15 12:12 UTC by nta808015

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-06-20 00:11 UTC, lokochaol commented on accounts/tests.py
>  #     def test_failure_post_with_empty_email(self):
def test_failure_post_with_empty_form(self):
def test_failure_post_with_empty_email(self):
...
など、[テスト項目要件整理](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=842149650)の「期待する効果」に対応するように、残りのテストの作成もお願いします！！

2023-06-20 00:27 UTC, lokochaol commented on accounts/tests.py
>  #     def test_failure_post_with_empty_email(self):
加えてですが、test.pyに残っているprint文等はプルリク出す時には消しちゃってください！

2023-06-26 06:42 UTC, nta808015 commented on accounts/tests.py
>  #     def test_failure_post_with_empty_email(self):
修正完了しました。確認をお願いしたいです。

2023-06-27 13:25 UTC, lokochaol reviewed
最後、tweetsのtestの方に、tweets/home/にgetした時のtestを書いてください！

2023-06-27 13:25 UTC, lokochaol commented on accounts/tests.py
> +        print(form.errors)
print文はプルリク出す時に消しちゃってください！

2023-06-27 13:25 UTC, lokochaol commented on accounts/tests.py
> +        print(form.errors)
同じくです！

2023-06-27 13:25 UTC, lokochaol commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
`<!-- base.htmlを継承 -->`
`<!-- -->`のタグの中に記述すると、htmlでもコメントを書くことができますよ！

2023-06-28 02:37 UTC, nta808015 commented on accounts/tests.py
> +        print(form.errors)
おそらくすべてのprint文を削除できたかと思います。

2023-06-28 02:38 UTC, nta808015 commented on accounts/tests.py
> +        print(form.errors)
上記と同じくすべてのprint文を削除できたかと思います。

2023-06-28 02:44 UTC, nta808015 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
初めて知りました！ありがとうございます！！
accounts/template内の.htmlのコメント文の書き方を修正しました！
ご確認をお願いしたいです！

2023-06-28 03:03 UTC, masaya09 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
横からですみません。少し気になったので確認です。python manage.py runserver を行なって画面上でユーザー登録ができているかは確認されてますか？

なぜこのような質問をしたのかというと、htmlでコメントアウトせずに文字をそのまま記述している場合、runserverしたときに画面表示するとそのまま表示されると思うのですが、そのときに気になりませんでしたか？画面上に不要な文言は通常削除すべきところになります。Notionの資料を見てそのままコピペするのは構わないのですが、最低限の調整は行って欲しいです。

今一度、python manage.py runserver で確認して、不要な文言がある場合は削除またはコメントアウトしてください

2023-06-28 04:50 UTC, nta808015 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
コメントありがとうございます！
まず私のミスで1,2回目にプルリクエストを提出する際にrunserverをして画面上でユーザー登録できているかを確認して以降の提出で、runserverを行うことが抜けてしまっていました。今後プルリクエストを提出する際は要件整理を満たしているかだけでなく、確認事項の方も全てもう一度確認した上で提出することを心がけます。
そして、最初にrunserverを行った際には要件整理での機能が実装されていることだけに執着しており、画面表記の分までお手本の画面と照らし合わせて注意深く確認することもできていなかったと思うため、こちらも今後プルリクエストする際にrunserverを行う時に全体を注意深く確認していきます。
また、runserverを行って不要なものがあれば編集を行っていきます。全て確認した際にはもう一度こちらとslackの方にコメントします。
最後に、今回コメントくださり本当にありがとうございます！！masayaさんのコメントから現状、自分には機能を実装するだけで確認する意識がかなり欠如していることを認識できました！これからもたくさん失敗を繰り返すと思いますが、少しずつ成長できるように尽力して参ります。
お手数をおかけしますが、今後もよろしくお願いします。

2023-06-28 07:46 UTC, lokochaol commented on tweets/tests.py
> +        self.client.login(username="testuser", password="testpass")
setUpでは使い回したい変数やどのメソッドのテストにも共通する部分を繰り返し記述することを避けます。https://www.notion.so/shinonome-inc/b6ce37a837614e03b8d6eb726a3338e0?pvs=4#e8f05de6b8be4c55b7a0fc5276c01e7c
なのでloginの処理はsetUpに入れておくといいと思います！

2023-06-29 13:31 UTC, lokochaol commented
LGTMです！

2023-06-29 13:32 UTC, nta808015 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
runserverして画面上でも異常がないか確認しました！

2023-06-29 13:32 UTC, nta808015 commented on tweets/tests.py
> +        self.client.login(username="testuser", password="testpass")
修正完了しました！

2023-06-29 15:37 UTC, masaya09 requested changes

2023-06-29 15:37 UTC, masaya09 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
まだ不要な文字残ってるので削除お願いします

2023-06-29 15:37 UTC, masaya09 commented on mysite/templates/accounts/signup.html
> +</form>
ここら辺も忘れずに

2023-06-29 15:37 UTC, masaya09 commented on mysite/templates/tweets/home.html
> +{% block title %}Home{% endblock %} ← titleを入れる
同様です

2023-06-29 15:37 UTC, masaya09 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは短すぎます。最低 8 文字以上必要です。", form.errors["password2"][0])
これより前のテストでは、エラーの文言確認のテストはassertInを用いてたのに、ここは assetEqual 使っていることは統一性の観点からよくないので、assertInに変更しておくのを勧めます。これは assertEqual で書くことがダメということではなく今まで assertIn で書いてるのでここも assertIn にしないとどうして実装が異なるのか、他の人から見たら勘繰ってしまうためです

2023-06-29 15:37 UTC, masaya09 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは ユーザー名 と似すぎています。", form.errors["password2"][0])
ここも

2023-06-29 15:37 UTC, masaya09 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは数字しか使われていません。", form.errors["password2"][0])
ここも

2023-06-29 15:37 UTC, masaya09 commented on accounts/tests.py
> +        self.assertEqual("確認用パスワードが一致しません。", form.errors["password2"][0])
ここも

2023-06-30 06:13 UTC, nta808015 commented on mysite/templates/accounts/signup.html
> +{% extends "base.html" %} ← base.htmlを継承
修正しました！

2023-06-30 06:13 UTC, nta808015 commented on mysite/templates/accounts/signup.html
> +</form>
修正しました！

2023-06-30 06:13 UTC, nta808015 commented on mysite/templates/tweets/home.html
> +{% block title %}Home{% endblock %} ← titleを入れる
修正しました！

2023-06-30 06:13 UTC, nta808015 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは短すぎます。最低 8 文字以上必要です。", form.errors["password2"][0])
修正しました！
たしかに、統一感がないとわかりづらいソースコードになってしまいますよね。
以後気を付けます！

2023-06-30 06:13 UTC, nta808015 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは ユーザー名 と似すぎています。", form.errors["password2"][0])
修正しました！

2023-06-30 06:13 UTC, nta808015 commented on accounts/tests.py
> +        self.assertEqual("確認用パスワードが一致しません。", form.errors["password2"][0])
修正しました！

2023-06-30 06:13 UTC, nta808015 commented on accounts/tests.py
> +        self.assertEqual("このパスワードは数字しか使われていません。", form.errors["password2"][0])
修正しました！

2023-06-30 07:22 UTC, masaya09 requested changes

2023-06-30 07:22 UTC, masaya09 commented on accounts/tests.py
> +        self.assertIn("確認用パスワードが一致しません。", form.errors["password2"][0])
assertInを用いる場合、[0]はつけなくていいです。[0]つけてしまうと、おそらくですが第１引数の方は、"確認用"とだけしても成功する可能性があります。つまり。1文字でもあってればTrueになるという状態になると思います。

他のところも修正してください

2023-07-01 06:07 UTC, nta808015 commented on accounts/tests.py
> +        self.assertIn("確認用パスワードが一致しません。", form.errors["password2"][0])
修正完了しました！確認をお願いしたいです！

2023-07-01 12:07 UTC, masaya09 commented on mysite/templates/accounts/signup.html
mysiteフォルダ内にtemplatesを作成したのはなぜですか？

2023-07-02 03:04 UTC, nta808015 commented on mysite/templates/accounts/signup.html
すみません！
作成した時にサインアップの資料に書いてある通りの階層構造にするために、注意深く作成していたと思っていましたが、資料をもう一度見返すと誤っていました。単純に作成ミスでした。修正致します。

2023-07-02 03:10 UTC, nta808015 commented on mysite/templates/accounts/signup.html
いや、違いますね。
templates作成はできているにも関わらず、mysiteの方にも同義なtemplatesが作成してしまっているということですね。
私の記憶だと、たしかtemplatesの作成場所を誤っていて修正した際に元々間違えていたものを削除することを忘れてしまっていたのだと思います。
不要な部分だと思うので削除して、もう一度プリリクエストを送ります！

2023-07-02 03:11 UTC, nta808015 commented on mysite/templates/accounts/signup.html
修正しました。確認お願いします！

2023-07-02 06:10 UTC, masaya09 approved these changes
LGTM

2023-07-02 06:11 UTC, merged