フォローアンフォロー機能実装
shinonome-inc/backend-final-assignment-Shintaro_Shimura pull request #8
Opened 2023-08-19 02:20 UTC by nta808015

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-19 10:26 UTC, SShizawa approved these changes

2023-08-19 10:26 UTC, SShizawa commented on templates/accounts/profile.html
>  {% extends "base.html" %}
全体的によく書けていると思います！

フォロワーとフォローの人数部分をクリックすると、フォローリスト・フォロワーリストに遷移するようにしてください。
フォロー一覧にフォローしたユーザーが表示されるようにしてください。フォロワー一覧も同じです。

2023-08-23 01:53 UTC, nta808015 commented on templates/accounts/profile.html
>  {% extends "base.html" %}
修正しました。確認お願いします。

2023-08-23 02:42 UTC, SShizawa requested changes

2023-08-23 02:42 UTC, SShizawa commented on templates/accounts/profile.html
> +</div>
フォロワー数をクリックした際に、フォロワー一覧が表示されるようにしてください。フォローも同様に修正してください。

2023-08-23 03:06 UTC, nta808015 commented on templates/accounts/profile.html
> +</div>
修正しました。確認お願いします。

2023-08-23 03:08 UTC, nta808015 commented on templates/accounts/profile.html
> +</div>
フォロー数と数字の部分を繋げてフォローリストが表示されるよう修正しました。フォロワーに関しても同様です。確認お願いします。

2023-08-24 02:08 UTC, Akinori13 requested changes
いくつかコメントしました！

2023-08-24 02:08 UTC, Akinori13 commented on templates/tweets/home.html
> +        <p>内容：{{ tweet.content }}</p>
このPRと関係はありませんが、linebreaksを利用すると改行のある表示ができますね。（修正は任意）

2023-08-24 02:08 UTC, Akinori13 commented on templates/accounts/profile.html
> +    <a href="{% url 'accounts:following_list' user.username %}">フォロワー数:{{followers_num}}</a>
リンク先が同一になっていますね

2023-08-24 02:08 UTC, Akinori13 commented on templates/accounts/following_list.html
> +    {% if following_friendship.following %}
FriendShipオブジェクトのfollowingフィールドはNULL許容していないので、`if following_friendship.following`で確認は不要かなと思ったのですが、何か理由はありますか？

2023-08-24 02:08 UTC, Akinori13 commented on templates/accounts/follower_list.html
> +    {% empty %}
👍

2023-08-24 02:08 UTC, Akinori13 commented on accounts/models.py
> +    following = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="follower")
`related_name`は複数形が一般です。また例えばfollowingへのrelated_nameをxとすると、
```
user.x = FriendShip.objects.filter(following=user)
```

みたいにFriendShipオブジェクトになるので、friendships_by_followingみたいな方が良いかと思います。

2023-08-25 03:06 UTC, nta808015 commented on templates/accounts/profile.html
> +    <a href="{% url 'accounts:following_list' user.username %}">フォロワー数:{{followers_num}}</a>
修正しました。

2023-08-25 03:31 UTC, nta808015 commented on templates/accounts/following_list.html
> +    {% if following_friendship.following %}
すみません確認不足でした！修正しました。
エラーチェックをしている時に、いろいろ書き換えてしまっていました。
最終的にfolloer_list.htmlのような書き方に合わせようとしていて、「if following_friendship.following」の部分を削除する工程が抜けてしまっていました。

2023-08-25 03:39 UTC, nta808015 commented on accounts/models.py
> +    following = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="follower")
修正しました。

2023-08-25 03:45 UTC, nta808015 commented on templates/tweets/home.html
> +        <p>内容：{{ tweet.content }}</p>
わかりました。

2023-08-25 05:26 UTC, Akinori13 requested changes
少しコメントしました！

2023-08-25 05:26 UTC, Akinori13 commented on accounts/models.py
> +        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_follower"
`friendships_by_following`ではなく、`friendships_by_follower`にした理由はありますか？

2023-08-25 05:26 UTC, Akinori13 commented on accounts/tests.py
> +class TestFollowingListView(TestCase):
ListViewに対するテストは複数データを作成してテストで個数の確認をするべきです。

2023-08-25 05:30 UTC, nta808015 commented on accounts/models.py
> +        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_follower"
followingとfollowerで書き換える箇所を間違えていました。
一応全て修正しましたが、related_nameの名前は統一しなければいけませんか？

2023-08-25 05:48 UTC, nta808015 commented on accounts/tests.py
> +class TestFollowingListView(TestCase):
修正しました。

2023-08-25 05:52 UTC, Akinori13 commented on accounts/models.py
> +        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_follower"
修正内容で問題ないです

2023-08-25 05:53 UTC, Akinori13 commented on accounts/tests.py
> +class TestFollowingListView(TestCase):
個数の確認はしましたか？

2023-08-25 05:54 UTC, nta808015 commented on accounts/models.py
> +        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_follower"
了解しました。

2023-08-25 06:11 UTC, nta808015 commented on accounts/tests.py
> +class TestFollowingListView(TestCase):
確認できていませんでした。申し訳ありません。
修正しました。runserverをして、複数ユーザーのfolllowingとfollowerをした際のリストへの反映の確認が取れました。

2023-08-25 06:20 UTC, Akinori13 approved these changes
LGTM

2023-08-25 06:20 UTC, merged