いいね機能実装
shinonome-inc/backend-final-assignment-Shintaro_Shimura pull request #9
Opened 2023-08-27 06:02 UTC by nta808015

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-27 11:02 UTC, ryo-thel reviewed
とても良いと思います！
数点コメントしましたので修正をお願いします！

2023-08-27 11:02 UTC, ryo-thel commented on tweets/views.py
>  class HomeView(LoginRequiredMixin, ListView):
ホームページをリロードするといいねをしていても強制的にいいねボタンが表示されてしまう点の修正とN+1の修正をお願いします！

2023-08-27 11:02 UTC, ryo-thel commented on tweets/tests.py
> +        self.assertTrue(Like.objects.filter(tweet=self.tweet, user=self.user).exists())
ここでのテストはデータが追加されていないかを確認するテストなので、データが存在するかを調べるのではなくデータの数が変化していないかを調べるべきだと思います！

2023-08-28 05:26 UTC, nta808015 commented on tweets/tests.py
> +        self.assertTrue(Like.objects.filter(tweet=self.tweet, user=self.user).exists())
修正しました。

2023-08-28 05:27 UTC, nta808015 commented on tweets/views.py
>  class HomeView(LoginRequiredMixin, ListView):
自信はないですが、ホームページをリロードしても強制的にいいねボタンが表示されてしまう点を修正しました。

2023-08-28 06:02 UTC, ryo-thel commented
1次レビューLGTMです!

2023-08-30 14:18 UTC, TAK848 requested changes

2023-08-30 14:18 UTC, TAK848 commented on templates/tweets/home.html
> +        {% include "tweets/like_js.html" %}
このjsをforの中にいれた理由を確認したいです！

2023-08-30 14:18 UTC, TAK848 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
related_nameが不適切です…。

related_nameは，tweet側からlikeを逆参照するときの名前であり，`xx_tweet`ではないです。また，複数形になるはずです。調べてみてください（そして今までの箇所なども，再度確認しておいてください。）
このままだと，ある特定のtweetのlikeを全て取得する時に，
`tweet.liked_tweet`のようになってしまいます

2023-08-30 14:18 UTC, TAK848 commented on tweets/views.py
> +            like.delete()
ifで分岐しなくてもdeleteできます...!!
不要なSQLを1つ減らせます。

2023-08-30 15:48 UTC, nta808015 commented on templates/tweets/home.html
> +        {% include "tweets/like_js.html" %}
jsの部分、修正しました。
1次レビューの際にhomeの画面でリロードすると、強制的にいいね解除ボタンがいいねボタンに切り替わってしまう問題を修正していた際に、そこの部分も修正しようとしていたのですが抜けていました。申し訳ありません。
jsをforに入れても動作は正常だったのですが、for内に入れると不要にscriptの記述を読み込んでしまいパフォーマンスが下がってしまうため、forの中には入れないと考えたのですが、解釈が違っていたら教えていただきたいです。

2023-08-30 15:50 UTC, nta808015 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
liked_tweetからlikesと複数形にして修正しました。
また、liked_userも複数形にするべきだと判断したため、likeusersとして修正しました。
今までの箇所の変更も修正しました。

2023-08-30 15:51 UTC, nta808015 commented on tweets/views.py
> +            like.delete()
修正しました。SQL一つ減らせたので少しだけスマートになった気がします！

2023-08-31 03:48 UTC, TAK848 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
複数形にしたのはOKです！そもそも，related_nameはtweetでもtweetsでもなく，likeです！
ある特定のtweetのlikeを全て取得する時に，
`tweet.xxxxxx`で，該当ツイートに対するlikeを全部引っ張る時などに使うんですが，`xxxxxx`に入るのには何が適切でしょうか…？
https://djangobrothers.com/blogs/related_name/

2023-08-31 03:53 UTC, TAK848 commented on tweets/migrations/0003_like_like_unique_like.py
> +                        related_name="likeusers",
過去に作ったmigrationをこのように訂正するのはあまり良くないです…（mainに入ってるものではないので絶対ダメ！ではないけど）
このように編集するくらいなら，migrations作り直した方が良いかと

2023-08-31 03:56 UTC, TAK848 commented on templates/tweets/home.html
> +        {% include "tweets/like_js.html" %}
不要なjsを何度も読み込んでしまいますよね，あってます!!
同名の変数を何度も宣言することになってしまいますよね…

2023-08-31 04:19 UTC, nta808015 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
参考資料の添付ありがとうございます！
xxxxxxに入るものはlikeusersだと思います。該当ユーザーのいlikeを全部引っ張るとは、特定のuserにいいねをしたuesrを全て表示するという風に解釈しました。添付して頂いた資料を参考にすると、userのlikeを逆参照するということは、クラス名ではなくrelated_nameを使用しなければならないため、自分のプログラムであればlikeクラスのuserをrelated_nameでlikeusersという風に定義しているため、xxxxxxにはlikeusersが該当するのではないかという結論に至りました。
誤っていたらもう一度資料読みなおします。

2023-08-31 04:19 UTC, nta808015 commented on templates/tweets/home.html
> +        {% include "tweets/like_js.html" %}
そうですよね！よかったです。
ありがとうございます。

2023-08-31 04:32 UTC, nta808015 commented on tweets/migrations/0003_like_like_unique_like.py
> +                        related_name="likeusers",
そうですよね。0003_like_like_unique_like.pyのmigrationsを作り直してコミットしたのですが、ファイルを消して作り直しただけなので、変更差分がないためpushできないと言われてしまいました。

2023-08-31 06:52 UTC, TAK848 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
-  逆参照なので，ここで定義したrelated_nameを使うのは，user側です。
-  userオブジェクトから，そのユーザーのlikeを全て引っ張りたいときに参照します。つまり，User側から自分たちをどう呼ぶのかを定義しているわけです
- 現状だとlikeusersになると言われれば，そう定義しているのでそうなのですが，その命名は適切でしょうか…？

2023-08-31 07:33 UTC, nta808015 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
そうですね、関連名はわかりやすくプログラム内で一貫性を持たせるという観点からすると適切ではないと思い、user側のrelated_nameの定義もtweetの方と合わせてlikesとして設定しました。
全体の修正も兼ねておりますが、変更するmigrationsを一旦削除して作り直していますが、変更差分としての表示はないと思われます。

2023-08-31 12:12 UTC, TAK848 commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liked_user")
フロー的には3,4,5全部消してからmakemigrationsした方がより良いと思いますが，内容としてはOKです！

2023-08-31 12:12 UTC, TAK848 approved these changes

2023-08-31 12:12 UTC, merged